# You can use a Docker image from Docker Hub or your own container registry
image: python:3.5.1
   
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt --use-mirrors
          - python manage.py migrate --noinput
          - python manage.py test
